### ISSUE TITLE
5.0.5.1 Coins Processing with Other Coin's Data

### ISSUE THREAD

**Issue by Kintak** [GuntharDeNiro/Gunthy#10]
I've stumbled on a bug that appears to be causing all coins to process with the data of the coin that was processed prior to it.

https://i.imgur.com/9i91hcr.png VIA processing with DASH's data (notice BBs)
https://i.imgur.com/jxkksnc.png BAT processing with CVC's data

After some diagnosing I found that it appears to relate directly to my list of pairs being processed. GB worked fine when it was running on one pair, but when running on my full list of 66 it started exhibiting this behavior. It also exhibited this behavior across both the bbstepgain and stepgain strategies (I did not test others).

**Comment by paramecie** [comment]
Does this corresponds to your problem?
#11

**Comment by GuntharDeNiro** [comment]
@paramecie yep fixed with this mornign commit, will build in a few

**Comment by paramecie** [comment]
Oh nice. Is it Bittrex that changed something or a GB internal problem?

**Comment by paramecie** [comment]
@GuntharDeNiro Thanks a lot! I've figured out my API problem here. Still remains the crazy prices in GB. Thanks for your support. But please try to have a nice Sunday!

**Comment by Kintak** [comment]
Bug appears to be fixed as of 5.0.5.4. Awesome work.
