### ISSUE TITLE
GUI Notifications/gui match core buy or sell

### ISSUE THREAD

**Issue by okkies** [GuntharDeNiro/Gunthy#113]
I keep getting spammed with messages: we can buy, yet its not buying. Then i check core, it gives me a reason we cannot buy. for example "GUNBOT RT says: Stochastic Oscillator is too high!!! Waiting to buy" 

Can we send the correct notification to the gui?
or even better show all the data core is pumping out each cycle inside the  the gui. so i can directly see why its not buying instead of going trough the logs

and if you got extra time, bring back okkies_mode

**Comment by adrianthomson2142** [comment]
Like updating the console callback to the pair in the GUI each cycle?
