### ISSUE TITLE
DCA_RESERVE request

### ISSUE THREAD

**Issue by cwcgunbot-com** [GuntharDeNiro/Gunthy#119]
* Add DCA_RESERVE that will reserve a part of total fund for DCA only, this wont be used to open new trades. 
* So we should have 2 kinds of funds reserve:
1) FUNDS_RESERVE: Gunbot cannot use this in any case.
2) DCA_RESERVE: Can be used for DCA only.
--------------
How to calculate these things:
(1) 
Available_fund_for_newTrade = (Total_fund) - (FUNDS_RESERVE) - (DCA_RESERVE)
(2) 
Available_fund_for_DCA = (Total_fund) - (FUNDS_RESERVE)
#corefeatures

**Comment by duongngocmanh** [comment]
How soon this will be added if it is approved ?

**Comment by lucidqdreams** [comment]
I have wanted a way to manage DCA trades for ages.  I have posted a few ideas this one is from dec 2017 https://github.com/GuntharDeNiro/BTCT/issues/333.  Not sure how these ideas are actually selected for development.  It would be nice to have some of these ideas collated and possibly voted on by the community.
