### ISSUE TITLE
5.0.5.4 828fd3f ECONNRESET

### ISSUE THREAD

**Issue by paramecie** [GuntharDeNiro/Gunthy#12]
Not  problem, happened once only after a 2 hours run.
Doesn't hang or whatever. Just signaling.

![2017-10-02 03_33_22-k__gunbot_gunthy_v5054_828fd3f_allos_gunthy exe](https://user-images.githubusercontent.com/32078594/31061567-0e5d4a46-a723-11e7-9da1-12f9d3cf393f.png)

BOT_DELAY=30
GUNTHY_API=true
Bittrex.

I'll edit if I see more of them.
Edit: still have this error from time to time...

**Comment by paramecie** [comment]
Today again, like one per hour, with 5.0.5.5 RC, just for your information.

**Comment by Dangerous-Mind** [comment]
Getting about 20 /hour.

Error on strategy BB for BTC-LTC on bittrex while getting ema2 -\ Error: RequestError: Error: read ECONNRESET

Error on strategy BB for BTC-LTC on bittrex while getting ema1 -\ Error: RequestError: Error: read ECONNRESET

and

Error on strategy BB for BTC-DGB on bittrex while getting Bollinger Bands -\ Error: RequestError: Error: read ECONNRESET

**Comment by JRBishop** [comment]
I was having this issue also. Went back to version 3.3.2 because of it.
