### ISSUE TITLE
Stops are not removed after closing a position

### ISSUE THREAD

**Issue by boekenbox** [GuntharDeNiro/Gunthy#122]
Stops set by STOP_BUY / STOP_SELL are not automatically cancelled/removed after a position closes successfully. 

Can cause unwanted behavior when a new position is opened afterwards.

**Comment by GuntharDeNiro** [comment]
@boekenbox despite I'm trying to find an api call from them to correct this (seems there is no way but I'm finding a workaround) I remind you stop positions are "per trade": it is effective only on the trade id it has been open from.
