### ISSUE TITLE
Feature Request - Max Simultaneous Trading Pairs

### ISSUE THREAD

**Issue by itonical** [GuntharDeNiro/Gunthy#131]
Max Simultaneous Trading Pairs

Set a max amount of trading pairs for GB to cycle through

![photo_2019-04-09_14-19-59](https://user-images.githubusercontent.com/5902157/55803632-a5096880-5ad2-11e9-8290-a267d4a4befe.jpg)

**Comment by lucidqdreams** [comment]
I would really like to see this or max trading pairs per exchange.  It could be added to your exchange settings and I can watch 20 pairs but I only want 2 open positions

**Comment by lucidqdreams** [comment]
Also what would be great is Max DCA positions occurring at one time.  I could have 5 max positions and I could have 5 max DCA, but I could also have 5 max positions and 2 max DCA.
