### ISSUE TITLE
5.0.5.5 Error: Period defined not available on bittrex

### ISSUE THREAD

**Issue by Dehumanizer77** [GuntharDeNiro/Gunthy#14]
I'm getting this error on bittrex with 15min period. Older versions worked with the same config, if I change period to 5 or 30 it works.

**Comment by Vaelek** [comment]
Period candlesticks were previously built by the bot, now they are fetched from the exchange. Bittrex doesn't support requesting 15m candle data unfortunately. To use 15m period, I believe you can enable the GUNTHY_API setting.
