### ISSUE TITLE
[bug] KuCoin - Average Bought Price is stuck and Gunbot selling at a loss

### ISSUE THREAD

**Issue by t0xicfume** [GuntharDeNiro/Gunthy#147]
In Gunbot on Kucoin, the value of ABP of BTC-ETH is stuck at 0.02903. Even though it bought at different price at each buy.

![image](https://user-images.githubusercontent.com/46041653/57327090-e5a0d580-70c2-11e9-87b2-8b3b08d1a941.png)

As a result, you can see Gunbot ended up selling at a loss. See screenshow below:

![image](https://user-images.githubusercontent.com/46041653/57327159-0e28cf80-70c3-11e9-9342-fc0b4551a23d.png)

Config, logs and json files: 
[Kucoin selling at loss due to static ABP bug.zip](https://github.com/GuntharDeNiro/Gunthy/files/3154257/Kucoin.selling.at.loss.due.to.static.ABP.bug.zip)

**Comment by GuntharDeNiro** [comment]
@t0xicfume found it, will push a fix with the upcoming release that fixes the same issue for Binance. Thanks for reporting
