### ISSUE TITLE
Feature Request - Add Beaxy exchange support

### ISSUE THREAD

**Issue by allanster** [GuntharDeNiro/Gunthy#156]
Please add Beaxy exchange support to Gunbot.

https://api-beta-doc.beaxy.com

**Comment by boekenbox** [comment]
@allanster cause you like trading in a ghost town?

**Comment by allanster** [comment]
@boekenbox 225,000 transactions per second per pair, comparable to Nasdaq and faster than anything else in crypto

Partnered with OneMarketData

Will have more order types than any crypto exchange in the world, plus advanced orders

Will have insurance and custody on both our business and major cold wallets

Will have 24/7 customer support and do not charge listing fees
