### ISSUE TITLE
5.0.5.5 RC socket hang up error

### ISSUE THREAD

**Issue by paramecie** [GuntharDeNiro/Gunthy#16]
Just view this error. 
![2017-10-03 14_55_15-k__gunbot_gunthy_v5055_rc_gunthy exe](https://user-images.githubusercontent.com/32078594/31126224-4d1d9dde-a84b-11e7-80bf-aea7b1667fef.png)

No GUI, local gunthy.exe (not on a server).

Config Bittrex (extracts):

		"debug": true,
		"BOT_DELAY": 25,
		"interval_ticker_update": 25000,
		"period_storage_ticker": 2000,
		"timeout_buy": 60000,
		"timeout_sell": 60000,
		"TV_GAIN": 0.6,
		"TV_TRADING_LIMIT_BUY": 0.001,
		"TV_PYRAMID": false,
		"TV_TRADING_LIMIT_SELL": 0.001,
		"TV_PROTECTION": true,
		"RETRY_TV_ORDER": false,
		"VERBOSE": true,
		"WATCH_MODE": false

			"PERIOD": 5,
			"EMA1": 12,
			"EMA2": 24,

Thanks for your help.

**Comment by utdrmac** [comment]
5055 started using the undocumented v2.0 bittrex API. If, like me, your upstream proxy service is filtering on /api/1.1/*, then this will bite you. #22

**Comment by paramecie** [comment]
Interesting. So we're building an RC for a stable final release on an undocumented not yet released API?

This is the exact opposite of used, verified, well known, documented, easily repaired or replaced: reliable.

You must know which computers are in space, moon, on voyager, in the ISS?
8086, 80386...
http://www.cpushack.com/space-craft-cpu.html

A bot is a robot: a machine. It should be able to work 24/7/365 reliably.

I guess this v2 API has been chosen to let users compare the bot BBs to the marketplace's ones?
Personnaly, I prefer an obscure BB and a working bot that I can tweak, than the opposite.

For 2 days now I'm back on the 3.3.2 version.
It's a PAIN but I know exactly its problems, but at least it runs, buys, and sells.

On 03 Oct with 5.0.5.5 RC I had 1 trade (1 sell), ONE.
Today 05 Oct with 3.3.2 I had 71 trades, and yesterday (afternoon) 19 trades.
Just probably because some pairs are updated every 5/10 minutes with 5.x :-(

(Sorry if myself I'm a pain. I really love Gunbot/Gunthy, hence my rant.)

**Comment by GuntharDeNiro** [comment]
@paramecie there are 3 ways to fetch datas from bittrex the way we need it: all  of them will be available. 1.- tickers array directly from v1.1 api => you need to trick interval tickers. 2.- gunthy api collecting tickers and building candles with close values on a serious box with dockers raffaele is building. 3.- v2. About the undocumented, unkown and those matters: by saturday night a complete documentation of the entire v5 is being posted at github wiki. Hope it helps yoru morale.

**Comment by GuntharDeNiro** [comment]
@GuntharDeNiro forgot to say: love you too

**Comment by paramecie** [comment]
@GuntharDeNiro 
Thanks for the detailed explanations. Understand your choices, they make sense. Please don't forget to deliver a default configuration adapted to beginners ;-)
I also understand Raffaele has a huge work to do in order to make a reliable history server... thank you Raffaele. But this server is really a nice idea!

Ah, and a documentation? But what, it's Christmas already??? :-)

Thanks for everything and your kind words.
