### ISSUE TITLE
5055 Buy moment too high with BBstepgain

### ISSUE THREAD

**Issue by svenberghuis** [GuntharDeNiro/Gunthy#24]
With BBstepgain on 5055 there was a buy moment way too high. BB Low was set to 10. Buy was in high BB region and above both EMA's.

Used settings:

"BOT_DELAY": 1,
"interval_ticker_update": 15000,
"period_storage_ticker": 2000,

"PERIOD": 5,
"BUY_LEVEL": 0.1,
"GAIN": 0.6,
"EMA1": 24,
"EMA2": 12,
"HIGH_BB": 40,
"LOW_BB": 10,
"STDV": 2,
"SMAPERIOD": 20,
"GUNTHY_API": false,
"DOUBLE_UP": false,
"MIN_VOLUME_TO_BUY": 0.0001,
"MIN_VOLUME_TO_SELL": 0.0001

![image](https://user-images.githubusercontent.com/32439383/31190265-eb830f64-a93a-11e7-9e30-fc14807f7084.png)

![image](https://user-images.githubusercontent.com/32439383/31189947-f3eba73e-a939-11e7-9f3a-e7a2396bac88.png)

**Comment by paramecie** [comment]
I think EMA1 and 2 are interverted in your config, see: #15 

Your "BUY_LEVEL" is very tiny, are you sure you want to buy 0.1% below the lowest EMA?

I don't know if it's related, just remarks.

**Comment by svenberghuis** [comment]
Inverted EMA's shouldn't matter. To my knowledge gunbot shouldn't buy if the price is above the lowest EMA. Is doesn't matter which of the two the lowest is. In the case above the buy is way above both EMA's and in the upper BB.

**Comment by paramecie** [comment]
Ermmm...

Does that really mean we have again a bot buying above LowBB, above EMA/GAIN limit ?

Sincerely, that would be really depressing.

**Comment by utdrmac** [comment]
@svenberghuis Check the bot output. There are other reports of bot's BB calculations being way off from exchange graphs. Could be the reason why you got action outside the bands. #27 #29

**Comment by svenberghuis** [comment]
Problem is I check the buy/sell actions way later and there currently is no way to check historical gunbot logs. All one can do now is report the problem without the actual gunbot output. Maybe Gunthar has an quick option to capture all output into a text file or something.

**Comment by GuntharDeNiro** [comment]
please report back on this after 5056: imo all of this is based on previous deifferent BB values than the chart you were loooking at. Now yu have gunbot getting same values than charts.
Thanks

**Comment by Dangerous-Mind** [comment]
Default BB 5055 settings (+ Double_up):
I don't think charts calculation settings can explain this chart.
It bought way higher then LowBB many times.

![image](https://user-images.githubusercontent.com/31196073/31317081-6ab2c2a8-ac32-11e7-87c2-67c9c7205fdf.png)

And I see this a lot of times. 

Buy price equal to sell price
![image](https://user-images.githubusercontent.com/31196073/31317102-a464b6b4-ac32-11e7-90ae-b406216e3b19.png)

{
	"event": "getting_public_trade_history",
	"exchange": "bittrex",
	"pair": "BTC-PIVX",
	"data": {
		"price_buy": 0.0008244356725867583,
		"price_sell": 0.00082443567
	},
	"error": false,
	"time": 1507466941957
}

I'll report back if it happens in 5056
