### ISSUE TITLE
5055 BB numbers vs exchange partially correct

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/Gunthy#27]
SMAPERIOD: 20, PERIOD: 5, EMA1: 16, EMA2: 8. Same configuration on exchange and in bot. You can see the numbers match for LowerBB. EMAs change with prices so they can be a bit off between graph and bot, I understand that. However, SMA and High BB should be calculated off previous 'close' arrays and only change per candle period.  SMA is off but HighBB is WAY off.

![badhighbb](https://user-images.githubusercontent.com/4413670/31196230-9abd132c-a912-11e7-8c38-aab7c809c659.png)

Why would HIGHBB be calculated so far off?

**Comment by paramecie** [comment]
Again, isn't EMA1 and EM2 interverted?
In the example Gunthar gave EMA1 is 1/2 of EMA2, not the opposite:
https://github.com/GuntharDeNiro/Gunthy/releases/tag/5055RC

**Comment by utdrmac** [comment]
According to people in chat, that shouldn't matter. Besides, BB isn't based off EMA; it is based off of SMA +/- STDEV

**Comment by paramecie** [comment]
Shouldn't matter?
We need an user guide :-(

Yes, I know how BB is calculated.
Just wondered.

**Comment by utdrmac** [comment]
Related #29

**Comment by GuntharDeNiro** [comment]
fixed on 5056
