### ISSUE TITLE
Please add ws/client true/false

### ISSUE THREAD

**Issue by miwi-fbsd** [GuntharDeNiro/Gunthy#28]
Hi,

While I was about to start a sec instance, i got a message about port conflict. Can you please add a flage for true or false? I am not keen running the web interface.

Thanks

**Comment by murm78** [comment]
@miwi-fbsd Try changing the port number in the config. Have one instance on port 5000, other on 5001, etc

**Comment by miwi-fbsd** [comment]
Yes that what I did, but I don't need the Web interface and keeping the ports open is a security risk. This option to have is a good thing.

**Comment by 3kynox** [comment]
Hello there !

This is already done on gui repository ( https://github.com/GuntharDeNiro/BTCT ) we now have option to set one hostname for gunbot  websocket connection with the GUI, and another one for remote connection with the gui (outside a vps for example).

You can't disable gunbot sending websocket messages for now. Enable or disable websockets messages from gunbot could be interesting to have if someone do not need any gui.

Let's  see what's Gunthar think of it.

Glossary purpose : For network vocabulary, any app that are set on a port don't open it, it uses and listen to it. However, depends of what's inside the config, if the hostname is set to 127.0.0.1, your port is open on a localhost IP, not accessible from outside, so ... That's all. The main firewall goal is to block inbound and / or outbound connection when using remote IP. So no security risk if it's closed.

**Comment by GuntharDeNiro** [comment]
this issue is not consistant: ws "emits" events locally on 5000 ports, it doesnt "open" that port to outbound connection. I take the part of disabling ws as a feature request for the sake to not have to change ports in config.js while you are not useing a gui: low priority for now, we stay focused on stability first.
