### ISSUE TITLE
BBSG Low BB calculation way off

### ISSUE THREAD

**Issue by selevanm** [GuntharDeNiro/Gunthy#29]
![ss1](https://user-images.githubusercontent.com/414673/31213067-35233e5a-a959-11e7-8c4d-2f9eef9a86af.jpg)
![ss2](https://user-images.githubusercontent.com/414673/31213069-36435be4-a959-11e7-84c9-e7df6256dc63.jpg)

See screenshots, low bb from gunthy_api reporting way lower than the actual chart on trex.  Verified that the sma-period values matched bb and the charting.  Its the same setup I have used on a lot of other pairs and those numbers are much closer.

**Comment by utdrmac** [comment]
Going to add mine in here too. These are WAAAY off overall.

![more badbbnumbers](https://user-images.githubusercontent.com/4413670/31235598-84b51e62-a9b7-11e7-8fdd-9f4a869ccbcb.png)

```
"bbstepgain": {
			"TRADING_LIMIT": 0.005,
			"PERIOD": 5,
			"BUY_LEVEL": 0.2,
                        "GAIN": 2,
                        "EMA1": 12,
		        "EMA2": 24,
			"HIGH_BB": 20,
			"LOW_BB": 30,
			"STDV": 2,
			"SMAPERIOD": 20,
			"BUYLVL1": 0.6,
                        "BUYLVL2": 2,
                        "BUYLVL3": 70,
			"SELLLVL1": 0.7,
			"SELLLVL2": 0.8,
			"SELLLVL3": 70,
			"BUYLVL": 2,
			"SELLLVL": 2,
			"LASTPOINTS": 10,
			"AVGPOINTS": 30,
			"AVGMINIMUM": 0.0000001,
			"PP_BUY": 0.00000001,
                        "PP_SELL": 0.12345678,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 600,
			"BUY_ENABLED": true,
                        "GUNTHY_API": false,
			"MIN_VOLUME_TO_BUY": 0.0001,
			"MIN_VOLUME_TO_SELL": 0.0001
		},
```

**Comment by GuntharDeNiro** [comment]
fixed: stay tuned on NB 5056
