### ISSUE TITLE
Exchanges

### ISSUE THREAD

**Issue by oefterdal** [GuntharDeNiro/Gunthy#3]
I have only a license for bittrex, Is it possible to remove the reference for other exchanges?
That would also clean up the WebGUI or at last set an exchange to default?

**Comment by sylance** [comment]
This probably should have been asked in Telegram.  Yes you can remove the other exchanges from the config file.  You'll have to keep the json format, meaning you'll have to remove a comma since it's not a list but a single entry now.  This is mine:

	"exchanges": {
		"bittrex": {
			"key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
		}

	},

**Comment by oefterdal** [comment]
I had done this, but still, shows up in WebGUI. Thanks. I will ask in Telegram next time.
