### ISSUE TITLE
5055 TV Dust error

### ISSUE THREAD

**Issue by Finnfj** [GuntharDeNiro/Gunthy#30]
on selling with pyramid set on true I get this:

2017/10/05 10:48:39: Looking for pending orders...
2017/10/05 10:48:39: Checking prices...
2017/10/05 10:48:39: Received a sell order...
[ { timestamp: 1507193318482,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-QTUM' } ]
2017/10/05 10:48:40 Checking for new emails ɢƱƝɃ๏Ł v5.0.5.5 TRADINGVIEWS Edition
Nothing to fetch
Error: HttpApiError: DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT
    at errorHandler (C:\snapshot\Gunbot-master\bittrex.js:0:0)
    at <anonymous>
undefined
undefined

**Comment by Rohobe** [comment]
This is an issue that occurs often also in my case...

**Comment by Finnfj** [comment]
After some communication with gunthar it was found that the sell limit is calculated in Altcoin, not in BTC so I close this and make a feature request instead
