### ISSUE TITLE
< Error: read ECONNRESET on 5.05.5   is anyone else having this issue? 

### ISSUE THREAD

**Issue by 1Cal** [GuntharDeNiro/Gunthy#31]
![untitled](https://user-images.githubusercontent.com/32552193/31245398-1e62cefc-aa02-11e7-826d-a1fab518ddee.png)

**Comment by paramecie** [comment]
Read before post ;-)

Yes: https://github.com/GuntharDeNiro/Gunthy/issues/12

**Comment by JRBishop** [comment]
I was having this issue also. Went back to 3.3.2 until 5.0.5 is more stable.

**Comment by GuntharDeNiro** [comment]
this issue will be fixed with the new gunthy api server
