### ISSUE TITLE
Enhancement: selllvl (and buylvl for stepgain) for double_up

### ISSUE THREAD

**Issue by jamesburkework** [GuntharDeNiro/Gunthy#32]
I use the following strategy for debagging:

Debag bbstepgain

                "bbstepgain": {
                        "TRADING_LIMIT": 0.001,
                        "PERIOD": 5,
                        "BUY_LEVEL": 0.1,
                        "GAIN": 2,
                        "EMA1": 48,
                        "EMA2": 24,
                        "HIGH_BB": 40,
                        "LOW_BB": 25,
                        "STDV": 2,
                        "SMAPERIOD": 50,
                        "BUYLVL1": 0.6,
                        "BUYLVL2": 2,
                        "BUYLVL3": 70,
                        "SELLLVL1": 0.8,
                        "SELLLVL2": 3,
                        "SELLLVL3": 70,
                        "BUYLVL": 2,
                        "SELLLVL": 1,
                        "LASTPOINTS": 15,
                        "AVGPOINTS": 750,
                        "AVGMINIMUM": 1e-8,
                        "GUNTHY_API": false,
                        "PP_BUY": 1e-8,
                        "PP_SELL": 0.12345678,
                        "PANIC_SELL": false,
                        "DOUBLE_UP": true,
                        "STOP_LIMIT": 60,
                        "BUY_ENABLED": true,
                        "MIN_VOLUME_TO_BUY": 0.0001,
                        "MIN_VOLUME_TO_SELL": 0.0001
                },

It would be good if i could set one sellvl and one buylvl for when im not debagging (in the process of double_up) and one selllvl and buylvl when GB is just trading, otherwise i have to override the strategy each time.

**Comment by paramecie** [comment]
I'm not sure about what you exactly mean.

But I'd recommand you for debagging, to save API resources etc.:

1° Either place manual sell orders on your marketplace, and remove the pairs from the bot

2° Or, copy the bot folder to another folder like "gunthy SELL ONLY", change its port in the config file, buy_enabled=false, add the bags pairs here with a SLOW turnover, like a pair every N minutes.
This way you've a specific global configuration for debagging, and a little use of your APIs. You also help your normal bot in decreasing the number of pairs it has to follow more carefully.

**Comment by jamesburkework** [comment]
double_up debags perfectly i don't need to do it manually, i just want it to auto-switch to a different buy/sell target once out of the debagging period.

**Comment by GuntharDeNiro** [comment]
i put this as a feature request but i give it low priority for now: we need to focus on stability before to implement new things that "might" break something else. Stay tuned!

**Comment by jamesburkework** [comment]
Fantastisch!

**Comment by paramecie** [comment]
Wunderbach!

**Comment by Utone** [comment]
zupahh
