### ISSUE TITLE
Feature request: "TV_TRADING_LIMIT_SELL" to be calculated in BTC not in ALT

### ISSUE THREAD

**Issue by Finnfj** [GuntharDeNiro/Gunthy#33]
At the moment "TV_TRADING_LIMIT_SELL" for the pyramid feature works with the value of the Altcoin to sell.
Running many pairs this doesn't work with Pyramid because of that.
If the bot were to calculate the equivalent amount of Altcoin from BTC using "TV_TRADING_LIMIT_SELL" and using that as the when getting a TV-sell signal we could use the feature in a more general fashion.

**Comment by GuntharDeNiro** [comment]
done
