### ISSUE TITLE
BB calculation bittrex inconsistently correct across pairs with same config

### ISSUE THREAD

**Issue by mekkanizm** [GuntharDeNiro/Gunthy#34]
Hi,

Having issues with BB calculations still. v5.0.55
Followed all readme instructions in release notes and I am running config for 5 min candles.
Some pairs calculate very closely to Bittrex BBs on chart on 5 minutes candles (BTC-ETH for example)

Others are way off the 5 minute chart BB values, but correct for one minute chart BB value. (just had a VTC buy at top of 5min BB band)

My config is the same for all pairs.
Any ideas?

"strategies": {
		"bb": {
			"TRADING_LIMIT": 0.02,
			"PERIOD": 5,
			"BUY_LEVEL": 0.1,
			"GAIN": 1.5,
			"EMA1": 12,
			"EMA2": 24,
			"HIGH_BB": 39,
			"LOW_BB": 25,
			"STDV": 2,
			"SMAPERIOD": 20,
			"BUYLVL1": 0.6,
			"BUYLVL2": 2,
			"BUYLVL3": 70,
			"SELLLVL1": 0.6,
			"SELLLVL2": 2,
			"SELLLVL3": 70,
			"BUYLVL": 2,
			"SELLLVL": 2,
			"LASTPOINTS": 5,
			"AVGPOINTS": 250,
			"AVGMINIMUM": 0.00000001,
			"GUNTHY_API": false,
			"PP_BUY": 0.00000001,
			"PP_SELL": 0.12345678,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.0005,
			"MIN_VOLUME_TO_SELL": 0.0005

**Comment by paramecie** [comment]
Strange...

As this 5.0.5.5 RC uses Bittrex API v2, maybe it gets the BB history from Bittrex - if it provides it, I don't know. Then, maybe, Bittrex sends erroneous/incomplete data for some specific pairs...

But just a comment, "BUY_LEVEL": 0.1 seems to me very dangerous.

**Comment by mekkanizm** [comment]
thanks.
buy level 0.1 is default and worked fine in 3.3 with pure bb.
have changed settings to 15 min candles and increased buy level now.
