### ISSUE TITLE
GB sometimes doesn't sell or buy some coins

### ISSUE THREAD

**Issue by Dangerous-Mind** [GuntharDeNiro/Gunthy#35]
![image](https://user-images.githubusercontent.com/31196073/31290875-f66cfea8-aac5-11e7-9b1c-565f729051db.png)

Sometimes GB doesn't sell coins even if they are withing range and it takes too much time to calculate the new values.

In de case above  (BB 60 - 40 with default configuration) I had to do a Panic Sell. It takes sometimes 5 mins or more to update the status even if the status of the coin is very close or above 0.0 to sell. 
So when the call is made that value have changed.
Even panic sell can take more than 5 mins (I had coins with 20 mins wait).

Other times there are error messages on the call that prevent the calculation and the sell/buy to be made and postponed till its to late.
(Ex: Error on strategy BB for BTC-UBQ on bittrex while getting Bollinger Bands -\ Error: RequestError: Error: read ECONNRESET)

Some coins never get bought even if they are within range.
I had coins that never got bought until I buy it manually. I had to sell it manually because GB showed the buying message when it was time to sell this coins. In the end he didn't buy or sell so I sold it using the Panic.

**Comment by Dangerous-Mind** [comment]
10 Mins no reply from the bot
![image](https://user-images.githubusercontent.com/31196073/31292489-8b7d80a8-aacb-11e7-80ff-5bae698fa94f.png)

15 Mins+ Replys with errors and a final reply a lot of time latter.
![image](https://user-images.githubusercontent.com/31196073/31292756-85307a24-aacc-11e7-9dde-a01e68550eb6.png)

At the same time other coins are being bought and sold (the above ETH was bought, sold and bought again after the panic button).

**Comment by paramecie** [comment]
Yes, unfortunately - a couple at least of issues has been opened because of strange/abormal cycling.
Ex: https://github.com/GuntharDeNiro/BTCT/issues/115
And I think Gunthar heard us, and he's doing his best on that also ;-)

**Comment by Dangerous-Mind** [comment]
I know. 
I just want to help and point were things are not working right so that he can fix it.

I'm a developer myself and I know that never ever a program comes out at 100%.
The only way it's 100% is if nobody tested it. And its much better to point were things are not OK so that they can be fixed then to give up and go back to 3.3.

In my case I like that people come to me and say that something is not working or it would be better that way.
At least I can fix and improve... And that's what keeps my job  :)

Got this also: Didn't sold for a long time... That hole is 10%+ dip and that mountain is 5%+ high.

![image](https://user-images.githubusercontent.com/31196073/31295052-0122760c-aad5-11e7-9104-df8e07c55074.png)

Thanks for your work Gunthar

**Comment by Dangerous-Mind** [comment]
Another one I just seen.
The price to sell jumps from the BB sell price calculated at that instant to the bought BB sell price (minimum sell price).

Bought price :**0.00778658**

2017/10/06 20:37:59: Last Bid/Price to sell: 0.00759702/**0.00783338**

2017/10/06 20:42:38: Last Bid/Price to sell: 0.00759251/**0.00760092**

2017/10/06 20:52:40: Last Bid/Price to sell: 0.00763305/**0.00783338**
