### ISSUE TITLE
TV_TRADING_LIMIT_SELL is not the ammount in BTC

### ISSUE THREAD

**Issue by mkarulin** [GuntharDeNiro/Gunthy#36]
All of my TV sell signals today have resulted in too little or no assets being sold. (v5.0.5.5) for BTC-The TV_TRADING_LIMIT_SELL is: 0.1 and it does not seem to be 0.1 BTC like TV_TRADING_LIMIT_BUY is.

One example: (0.01 ETH balance, TV_TRADING_LIMIT_SELL: 0.1)

2017/10/06 18:30:14 Checking for new emails ɢƱƝßѺŦ v5.0.5.5 TRADINGVIEWS Edition 
2017/10/06 18:30:14 Done
emailParsed { timestamp: 1507314614346,
  type: 'sell',
  exchange: 'bittrex',
  pair: 'BTC-ETH' }
2017/10/06 18:30:14 Done fetching all messages!
[ { timestamp: 1507314614346,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' } ]
2017/10/06 18:30:14: Looking for pending orders...
2017/10/06 18:30:15: Checking prices...
2017/10/06 18:30:15: Received a sell order...
[ { timestamp: 1507314614346,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' } ]
Error: HttpApiError: DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT
    at errorHandler (/snapshot/gunbot-build/bittrex.js:0:0)
    at <anonymous>
undefined
undefined
2017/10/06

**Comment by GuntharDeNiro** [comment]
@mkarulin fixed in 5056: tv trading limit is now calculated in BTC. While you wait: set pyramid off

**Comment by paramecie** [comment]
TV is bad anyway - we threw ours away 15 years ago, and are happier everyday.

**Comment by Exquitas** [comment]
@paramecie I have no issues at all with Tradingview
