### ISSUE TITLE
Correct build naming typo to Tonightly Build

### ISSUE THREAD

**Issue by Utone** [GuntharDeNiro/Gunthy#37]
small typo, but still its Tonightly

**Comment by paramecie** [comment]
Is it me, the language, context, but I don't understand?

**Comment by utdrmac** [comment]
Tonightly is not a word.

**Comment by Utone** [comment]
No of course you are right, it's makes total sense when you know the context, it's more an improvement and a name in one, with capital T, (it's a reference to earlier many many...many... builds that were to be released ''tonight" for well at least 2-3 weeks :D...

Just like well tonight...for example :)

So "Tonightly" is a more fitting, friendly, and 'phun' update to the Nightly standard in this case..
Just because we love to hear gun say it.

**Comment by paramecie** [comment]
Thanks both!
