### ISSUE TITLE
5055 Please display correct state of bot consistently

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/Gunthy#38]
This has been happening actually for quite some time, even back to version 4. The "table" says "Buy cycle" but the wording above says "We are on level 2 to sell". Those are contradictory. Please be consistent in showing us exactly what the bot is doing. If we are in BUY mode, there should not be any mentioning of "sell". Same for SELL mode, no mentioning of buy.

This fix is needed for a stable release. You can't have misinformation displayed. It's confusing.

![level2tosell](https://user-images.githubusercontent.com/4413670/31312438-d51da022-ab88-11e7-99c4-e75cc216e659.png)

**Comment by paramecie** [comment]
Yes, and opportunities...
https://github.com/GuntharDeNiro/BTCT/issues/130

**Comment by lowviz** [comment]
Open Orders should not be present when there are no open orders as well
