### ISSUE TITLE
Error on strategy BB for BTC-RISE on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

### ISSUE THREAD

**Issue by zachtdavis** [GuntharDeNiro/Gunthy#40]
3.3.2 runs great, cant get this latest version to play nice on windows 10

(key is fine, secret is fine, config file is valid, everything is fine)

I got it running with node, the GUI on 3000 works fine, then I hit start, and the terminal in the bg shows this for all pairs:

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢՍÑɮøŦ v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:21:39
------------------------------------------------------------------------------------------------

stdout: 2017/10/07 23:21:39: BTC-ARK Last Bid/Ask 0.00055400/0.00055407

stdout: Error on strategy BB for BTC-ARK on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

stdout: ------------------------------------------------------------------------------------------------
 ɢՍҊßǾͳ v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:21:44
------------------------------------------------------------------------------------------------
2017/10/07 23:21:44: BTC-ARK Last Bid/Ask 0.00055400/0.00055407

stdout: Error on strategy BB for BTC-ARK on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢƱΠɃøŁ v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:21:49
------------------------------------------------------------------------------------------------

stdout: 2017/10/07 23:21:49: BTC-STRAT Last Bid/Ask 0.00088217/0.00088278

stdout: Error on strategy BB for BTC-STRAT on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢƱͶ฿๏Ł v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:21:54
------------------------------------------------------------------------------------------------

stdout: 2017/10/07 23:21:54: BTC-TRST Last Bid/Ask 0.00007550/0.00007576

stdout: Error on strategy BB for BTC-TRST on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢՍҊ฿ѺŁ v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:21:59
------------------------------------------------------------------------------------------------

stdout: 2017/10/07 23:21:59: BTC-STRAT Last Bid/Ask 0.00088217/0.00088278

stdout: Error on strategy BB for BTC-STRAT on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢƱŋßםŦ v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:22:04
------------------------------------------------------------------------------------------------

stdout: 2017/10/07 23:22:04: BTC-XVG Last Bid/Ask 0.00000142/0.00000143

stdout: Error on strategy BB for BTC-XVG on bittrex while getting ema2 -\ Error: Cannot read property '0' of null

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢƱͶβѺͳ v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:22:09
------------------------------------------------------------------------------------------------

stdout: 2017/10/07 23:22:09: BTC-QTUM Last Bid/Ask 0.00271501/0.00272000

stdout: Error on strategy BB for BTC-QTUM on bittrex while getting balances -| Error: StatusCodeError: 503 - "The service is unavailable."

stdout: ------------------------------------------------------------------------------------------------

stdout:  ɢՍŋƁ๏Ł v5.0.5.5  Scanning bittrex for trading opportunities 2017/10/07 23:22:10
------------------------------------------------------------------------------------------------

stdout: Error on strategy BB for BTC-LISK on bittrex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...

**Comment by Dangerous-Mind** [comment]
Known glitch on the config.js

Gunbot Can't find EMA2 variable.

Check if you have two EMA1 on each pair inside the config.js file.
Change the second EMA1 to EMA2 or add EMA2 (default 12)

**Comment by zachtdavis** [comment]
JESUS youre my hero. I honestly tried to find this error before posting it in the open issues and whatever I was searching for wasnt pulling anything up.

THANK YOU!

**Comment by smportis** [comment]
Written a different way: in the Config.js file on 5.0.5.5, there was a type where the title of EMA2 says "EMA1":

"EMA1": 24,
"EMA1": 12,

Change it to say "EMA2" as shown below:

"EMA1": 24,
"EMA2": 12,

**Comment by zachtdavis** [comment]
Thank you as well, im stunned at how responsive everyone is to this issue! Wish the guy who is SELLING IT would address this as fast as you guys did :)
