### ISSUE TITLE
Enhancement: Enable partial profit taking levels

### ISSUE THREAD

**Issue by murm78** [GuntharDeNiro/Gunthy#43]
It's like stepgain for profit.

"SELLLEVEL1" : 0.6
"SELLLEVEL2" : 1
"SELLLEVEL3" : 2.5
"PROFITLEVEL1" :  10
"PROFITLEVEL2" : 20
"PROFITLEVEL3" : 50

When the price rises above a sell level, that sell level becomes our stop loss. Just like now. However, when trend watcher (or TV plugin) triggers a sell, only sell a specified % of your position. Wait to see if the price really drops back down to your stop, or keeps rising. 

If the price continues to rise past the next sell level, that becomes our new stop loss and we sell a greater % of our position when trend watcher or TV plugin triggers the next sell.

Why do this instead of lock in all of our profits at the first opportunity? Well let's check out BTC-USDT:

![image](https://user-images.githubusercontent.com/31592215/31350493-43311d2e-acdc-11e7-842e-43abb271ea29.png)

Right now, we can adjust trend watcher so it might not trigger a sell at the first hump circled in green. However in other situations, those same trend watcher settings would lead to sub-optimal sells, missing the peaks that rise above our sell levels and waiting until the price drops back down before locking in our profit.

I feel that this feature can make our strategies more bulletproof and profitable. Instead of focusing only on microprofits or larger swings, we can get the best of both worlds. 

Setting PROFITLEVEL1 to 100 would make stepgain act the same way it does now.

**Comment by Utone** [comment]
While I didn't read it all. A picture paints a thousand words: This we need!
To clear the to biggest of bags. +1

**Comment by wirmola** [comment]
I concur totally. Also to make all 3 levels of stepgain working at the same time together with this would be really cool.. Or maybe even a fourth PROFIT/BUY/SELLLEVEL?
