### ISSUE TITLE
Buy trade but no buy or order

### ISSUE THREAD

**Issue by Dangerous-Mind** [GuntharDeNiro/Gunthy#47]
I saw several buy trade messages for some minutes but there was no buy and no order on bittrex.
I had to buy it manually.

**Comment by paramecie** [comment]
Please don't bother to give us much detailed info - the Devs have a working crystal ball, of course!

**Comment by Dangerous-Mind** [comment]
I usually give all the detail I have but in this case the Gui didn't give me any information.
All the messages from the gui console were empty. And the Gunbot doesn't throw any messages.

I received:
Getting TA (empty)
Buy trade (also empty)

Some seconds latter again.. Checking ema, ... The Getting TA, Buy trade and nothing.

**Comment by paramecie** [comment]
Version, at least???

If 5.x please set gunthy_api = false.

**Comment by Dangerous-Mind** [comment]
This is 5.0.5.5 version Issues. I presume it's the 5.0.5.5 version I'm reporting.

Configuration:
	"bot": {
		"debug": false,
		"BOT_DELAY": 1,
		"interval_ticker_update": 25000,
		"period_storage_ticker": 2000,
		"timeout_buy": 60000,
		"timeout_sell": 60000,
		"TV_GAIN": 0.6,
		"TV_TRADING_LIMIT_BUY": 0.001,
		"TV_PYRAMID": false,
		"TV_TRADING_LIMIT_SELL": 0.001,
		"TV_PROTECTION": true,
		"RETRY_TV_ORDER": false,
		"VERBOSE": true,
		"WATCH_MODE": false
	},

                       "BTC-ARK": {
				"strategy": "bbstepgain",
				"override": {
					"TRADING_LIMIT": 0.005,
					"PERIOD": 5,
					"BUY_LEVEL": 0.1,
					"GAIN": 0.6,
					"EMA1": 24,
					"EMA2": 12,
					"HIGH_BB": 40,
					"LOW_BB": 40,
					"STDV": 2,
					"SMAPERIOD": 20,
					"BUYLVL1": 0.6,
					"BUYLVL2": 2,
					"BUYLVL3": 70,
					"SELLLVL1": 0.6,
					"SELLLVL2": 1.6,
					"SELLLVL3": 70,
					"BUYLVL": 2,
					"SELLLVL": 2,
					"LASTPOINTS": 5,
					"AVGPOINTS": 250,
					"AVGMINIMUM": 1e-8,
					"GUNTHY_API": false,
					"PP_BUY": 1e-8,
					"PP_SELL": 0.12345678,
					"PANIC_SELL": false,
					"DOUBLE_UP": false,
					"STOP_LIMIT": 6,
					"BUY_ENABLED": true,
					"MIN_VOLUME_TO_BUY": 0.0001,
					"MIN_VOLUME_TO_SELL": 0.0001
				}
			},

**Comment by paramecie** [comment]
min_volume should be 0.0005 otherwise it CANNOT trade on Bittrex.

buy_level 0.1 is dangerous, I'd be you, I try 2 or 3% under the lowest EMA.

**Comment by Dangerous-Mind** [comment]
I have it running on other coins.
But time to time I have that problem with the bot not buying but didn't see any message. Probably this GUI shows more errors.

Yeah you are right. It's the min value.

I've had problems with gunbot buying on pumps (just stopped one).
Probably buy_level 2 or 3 would help.

Thanks paramerice 👍 

This is mostly the default config.js.
Can you change this things on the config.js of next versions so that people don't have the same problems?

**Comment by Dangerous-Mind** [comment]
Changed the settings but I had the same problem in another coin.


2017-10-11 01:53:41	 **Buy trade**	
2017-10-11 01:53:50	 Getting order book	
2017-10-11 01:53:51	 Getting balances	
2017-10-11 01:53:55	 Getting ema 1	
2017-10-11 01:54:02	 Getting ema 2	
2017-10-11 01:54:10	 Getting ta	
2017-10-11 01:54:10	 Getting public trade history	
2017-10-11 01:54:10	 Gettting trade history	
2017-10-11 01:54:11	 Getting open orders	
2017-10-11 01:54:11	 Getting public trade history	
2017-10-11 01:54:11	 Getting ta	
2017-10-11 01:54:11	 **Buy trade**	
2017-10-11 01:55:01	 Getting order book	
2017-10-11 01:55:02	 Getting balances	
2017-10-11 01:55:09	 Getting ema 1	
2017-10-11 01:55:16	 Getting ema 2	
2017-10-11 01:55:23	 Getting ta	
2017-10-11 01:55:23	 Getting public trade history	
2017-10-11 01:55:23	 Gettting trade history	
2017-10-11 01:55:24	 Getting open orders	
2017-10-11 01:55:24	 Getting public trade history	
2017-10-11 01:55:24	 Getting ta	
2017-10-11 01:55:24	 **Buy trade**

I can see this info from the last Buy cycle
{
	"event": "getting_order_book",
	"exchange": "bittrex",
	"pair": "BTC-EMC2",
	"data": {
		"price_ask": 0.00001442,
		"price_bid": 0.00001453
	},
	"error": false,
	"time": 1507683301725
}

{
	"event": "getting_ema_1",
	"exchange": "bittrex",
	"pair": "BTC-EMC2",
	"data": {
		"ema": 0.000014809049815527539
	},
	"error": false,
	"time": 1507683309351
}
{
	"event": "getting_ema_2",
	"exchange": "bittrex",
	"pair": "BTC-EMC2",
	"data": {
		"ema": 0.000014765380715777518
	},
	"error": false,
	"time": 1507683316805
}

{
	"event": "getting_public_trade_history",
	"exchange": "bittrex",
	"pair": "BTC-EMC2",
	"data": {
		"price_buy": 0.00001461165120575446,
		"price_sell": 0.00001750568
	},
	"error": false,
	"time": 1507683323665
}

{
	"event": "buy_trade",
	"exchange": "bittrex",
	"pair": "BTC-EMC2",
	"data": {
		"amount": 345.30386740331494,
		"price": 0.00001448
	},
	"error": false,
	"time": 1507683221800
}

			"BTC-EMC2": {
				"strategy": "bbstepgain",
				"override": {
					"TRADING_LIMIT": 0.005,
					"PERIOD": 5,
					"BUY_LEVEL": 0.3,
					"GAIN": 0.6,
					"EMA1": 24,
					"EMA2": 12,
					"HIGH_BB": 40,
					"LOW_BB": 40,
					"STDV": 2,
					"SMAPERIOD": 20,
					"BUYLVL1": 0.6,
					"BUYLVL2": 2,
					"BUYLVL3": 70,
					"SELLLVL1": 0.6,
					"SELLLVL2": 1.6,
					"SELLLVL3": 70,
					"BUYLVL": 2,
					"SELLLVL": 2,
					"LASTPOINTS": 5,
					"AVGPOINTS": 250,
					"AVGMINIMUM": 1e-8,
					"GUNTHY_API": false,
					"PP_BUY": 1e-8,
					"PP_SELL": 0.12345678,
					"PANIC_SELL": false,
					"DOUBLE_UP": false,
					"STOP_LIMIT": 6,
					"BUY_ENABLED": true,
					"MIN_VOLUME_TO_BUY": 0.0005,
					"MIN_VOLUME_TO_SELL": 0.0005
				}
			},

**Comment by Exquitas** [comment]
Please post the log of Gunbot and not from some third party app ... Gunbot usually shows an error message that can tell us where the error could be while this log says almost nothing.

**Comment by Dangerous-Mind** [comment]
Is there a log on gunbot?
I've asked for it and no one could tell me were is it.
Also seen people complaining about not having a log.

Just tell me were it is since I have other pairs with the same problem.

**Comment by paramecie** [comment]
Enlarge gunthy at the maximum, then use:
https://snag.gy/

Yes, this is the log :-(

**Comment by Dangerous-Mind** [comment]
Lol.
My GB window is black. No info.

I once was contracted to fix an program to a bank that had no log errors. 

It had a bunch of try catch without throwing anything. It didn't do what he was supposed to do but at least it had no errors. 😊

By the way. A reply to your message on another post (blocked). 
I didn't drop de bags. I just invested them on a better one.. Bitcoin 

Now seriously. 
You have to chose to lose 6% that could turn to 20% or you can get the money back and reinvest and profit from it. 
On that same coin I had earned 10% that day. 
Then GB bought 2 times on two pumps before the drop. Almost the sold price. 
You can lose that bet and keep earning on another one or you can wait for something that might never happen to not lose x%

**Comment by paramecie** [comment]
>My GB window is black. No info.

Ah, because you're using a external GUI.
I don't, and it shows many things.
