### ISSUE TITLE
Stop limit not working

### ISSUE THREAD

**Issue by Dangerous-Mind** [GuntharDeNiro/Gunthy#49]
Stop limit does not work...

![image](https://user-images.githubusercontent.com/31196073/31452458-dfb7c7da-aea6-11e7-9153-8c9f2a2cf465.png)

![image](https://user-images.githubusercontent.com/31196073/31452489-f54e46aa-aea6-11e7-99aa-9342e30eb787.png)

**Comment by paramecie** [comment]
https://github.com/GuntharDeNiro/BTCT/issues/138

So, if you changed this value after having run gunthy, try to close it/run it?

**Comment by Dangerous-Mind** [comment]
I've set it for some days. And I'm using the GUI with several instances ( the instances stalled from time to time so I activated that feature). And this feature stops gunbot from time to time.
I don't think its that.

I had seen this a week ago. But I was not sure because I had a lot of bags from the past and didn't think It would pick up old bags.

But I did a full sell this week to do a fresh restart. And I started that coin yesterday.
Only using 6 pairs or so to minimize the problems and because there are still a lot of fixes to do on this version.

You probably thinks I keep complaining about everything but I really have to get things fixed.
I invested money on this and believe in the project. I think it has a great future but this bugs need to be cleared out.
And we are losing money on them all the time.

Waiting forward to have a new version...

**Comment by GuntharDeNiro** [comment]
@Dangerous-Mind i'm sorry guys, i am not going to support this kind of trolling. You should please understand some simple concept before to post something like this. And no: i am not going to repeat again what are the simple concepts i'm talking about here. Closing this issue and not wanting to see this open again without a solid base of "constructive" behaviours. Thank you.

**Comment by GuntharDeNiro** [comment]
Money you have invested is nothing about a beta version over a nightly build repo. Please stick on v3.3.2
Thank you

**Comment by paramecie** [comment]
>And we are losing money on them all the time.

Selling at loss is definitively NOT a solution to this.
