### ISSUE TITLE
[5.0.5.5] Multiple buy BBStepgain / DOUBLE_UP - 4 buys in a row

### ISSUE THREAD

**Issue by Dangerous-Mind** [GuntharDeNiro/Gunthy#50]
4 buys at a similar price some hours apart.
And several buys much higher them the value it was supposed to buy (buy close to sell).

![image](https://user-images.githubusercontent.com/31196073/31465046-b4e6594e-aeca-11e7-9681-1237fd4219f2.png)
![image](https://user-images.githubusercontent.com/31196073/31465052-baac5568-aeca-11e7-8933-9210eab2e008.png)
![image](https://user-images.githubusercontent.com/31196073/31465070-c1a5212e-aeca-11e7-8f28-af4df4e65441.png)

      "BTC-QTUM": {
			"strategy": "bbstepgain",
			"override": {
				"TRADING_LIMIT": 0.01,
				"PERIOD": 5,
				"BUY_LEVEL": 0.3,
				"GAIN": 0.6,
				"EMA1": 24,
				"EMA2": 12,
				"HIGH_BB": 40,
				"LOW_BB": 45,
				"STDV": 2,
				"SMAPERIOD": 20,
				"BUYLVL1": 0.6,
				"BUYLVL2": 2,
				"BUYLVL3": 70,
				"SELLLVL1": 0.6,
				"SELLLVL2": 1,
				"SELLLVL3": 70,
				"BUYLVL": 2,
				"SELLLVL": 2,
				"LASTPOINTS": 5,
				"AVGPOINTS": 250,
				"AVGMINIMUM": 1e-8,
				"GUNTHY_API": false,
				"PP_BUY": 1e-8,
				"PP_SELL": 0.12345678,
				"PANIC_SELL": false,
				"DOUBLE_UP": true,
				"STOP_LIMIT": 6,
				"BUY_ENABLED": true,
				"MIN_VOLUME_TO_BUY": 0.0005,
				"MIN_VOLUME_TO_SELL": 0.0005
			}
		},

**Comment by Exquitas** [comment]
Set Double_Up to false ....
@GuntharDeNiro close please

**Comment by Dangerous-Mind** [comment]
I thought you needed feedback on things to fix.
I've seen a lot of messages of Gunthar asking to report bugs here on github...

I know that I can stop the problem by closing the Double_Up but that doesn't solve the problem.
