### ISSUE TITLE
no data in /listener with Gunthy_v5055_RC_8ab53b2 on raspian, OSX and WIN

### ISSUE THREAD

**Issue by vivrelib** [GuntharDeNiro/Gunthy#52]
1. starting Gunthy_v5055_RC_8ab53b2
2. node app.js
=> Gunthy listening on 127.0.0.1 port 3000!
3. http://localhost:3000/listener
=> No Data is shown.

<img width="1235" alt="screen shot 2017-10-14 at 14 52 07" src="https://user-images.githubusercontent.com/30468916/31577151-ce673c3a-b109-11e7-81e8-86a396f60092.png">

**Comment by Banditozik** [comment]
same here

**Comment by dkgeorge** [comment]
As described in the user guide:

If you have set an external IP or hostname in the config file, and are seeing empty values or “??” in the WebGUI, then visit https://your_webUI_io_or_hostname:5000 and add the browser exception to the security alert you will be notified about. Then retry connecting to the WebGUI.

**Comment by Banditozik** [comment]
Unable to connect - can't establish connection to server at 127.0.0.1:5000

**Comment by 3kynox** [comment]
@Banditozik : @dkgeorge said `https://` and not just http. If it's accessed from outside a VPS, means no 127.0.0.1 but instead the hostname of your VPS or the remote IP as well.

**Comment by Banditozik** [comment]
m8 I used https and http, and external IP and localhost, and still nothing.
