### ISSUE TITLE
BB High and low

### ISSUE THREAD

**Issue by Dangerous-Mind** [GuntharDeNiro/Gunthy#53]
BB high and low doesn't make sense and are bugged.
According to some information BB should have there 100% at the middle.

But it doesn't happen.
If I set High BB to 100 ti goes to the place where the lower BB is at zero.
![image](https://user-images.githubusercontent.com/31196073/31581809-3c68328c-b16b-11e7-9254-efc16d72d7f7.png)

This afternoon, to put both BB at the middle I had to put High at 50 and low at 100.

At this moment I need to put both at 50 to get them in the middle (buy price = sell price).
![image](https://user-images.githubusercontent.com/31196073/31581880-f447e54a-b16c-11e7-9b6b-4e7c2096caa4.png)
![image](https://user-images.githubusercontent.com/31196073/31581892-261fae40-b16d-11e7-99e6-4c5eb31e3296.png)

**Comment by paramecie** [comment]
I'm not sure to understand, but:

The BB bandwidth (HighBB - LowBB) = 100%
The "middle" (the SMA line) is then 50%

As an example, buying at 25% LowBB means buying from 0 to 1/4th of the distance HighBB//LowBB from LowBB.
Hoping it's clear?

**Comment by utdrmac** [comment]
@Dangerous-Mind BB middle of 50 has been that way since Gunbot 3.3. HIGHBB of 0 == the high band line itself. LOWBB of 0 == the low band itself. LOWBB10 == 10% "inside" the low band. 50/50 == SMA.

**Comment by dkgeorge** [comment]
The BBs are indeed crazy and bugged. It may be working for other exchanges but at least for bittrex it doesn't make any sense. It is unusable, see this [post](https://gunthy.org/index.php/topic,1688.0.html)

**Comment by Dangerous-Mind** [comment]
According to the manual 100% should be in the middle for both.
And it doesn't make sense. In the first image to put in the middle I putted 100% and 50%.

On pump times they almost touche each other and makes a the bot buy the minute it falls a inch.

Or get this:
![image](https://user-images.githubusercontent.com/31196073/31627624-ca6595b2-b2a5-11e7-884b-d2e1002699da.png)

![image](https://user-images.githubusercontent.com/31196073/31627650-e2e359f8-b2a5-11e7-954e-e28f2a1b9475.png)

{
	"event": "getting_public_trade_history",
	"exchange": "bittrex",
	"pair": "BTC-XRP",
	"data": {
		"price_buy": 0.000048713973390450544,
		"price_sell": 0.000048747391
	},
	"error": false,
	"time": 1508177245664
}

**Comment by Exquitas** [comment]
@Dangerous-Mind i kindly ask you to pm me on telegram @exquitas in case of questions ......

**Comment by dkgeorge** [comment]
Exact same thing happened to me. It bought as soon as it sold in the same candle at the top of it (short time).
Gunthar confirmed yesterday in the Elite telegram group that BBs in 5055 are unfortunately broken.

**Comment by Singman33** [comment]
Dont get me wrong but it 14 days after releasing version 5.0.5.5 !
I will never understand why some guys are releasing a project with at least  a serie of tests with sample datas....

**Comment by utdrmac** [comment]
@dkgeorge He confirmed BB calculation is broken in 5055? Damn. Missed that. So, should we downgrade to 5053 if we want proper BB calculations? (i've been using bbstepgain)

**Comment by Dangerous-Mind** [comment]
> @Dangerous-Mind i kindly ask you to pm me on telegram @Exquitas in case of questions ......

I talked to Narkotix about this issue.
I followed his instructions then realized nothing was making seance and then made some simple tests.
Putted all at 0, then at all at 100. To center both I had to put 50 and 100.

Told him about the results and he told me he was reporting so I added a report to be fixed on the next versions.

I have my bot on test mode. Not buying anything atm. 
Every time I start it and it gets a pump he sell's then buys at the top when it starts to drop and I get another bag at higher price.

**Comment by Exquitas** [comment]
@Dangerous-Mind The space between the two Bollinger Bands = 100
So it's logical that BB_low = 50 and BB_high = 50 hit the middle (Sellprice = Boughtprice)

Also don't rely on plugins like Sjakil for BB's... They are there to give you an Idea of what GB sees.

If you really want to see what Gunbot sees, look at the logs, check where BB_High and BB_Low are and then look on the exchange Chart where it is (to see if they are too close etc)

Also GB has to calculate it's own BB Bands (because the Exchanges don't provide the BB Values over API). So it depends on your settings (on what you give to Gunbot to do it's calculations) where your BB's are located. In the newer upcoming versions it will be possible to match BBs with those on the exchanges. (It is already possible, somehow and there are Tutorials on this on our Board on how to achieve this)

**Comment by Singman33** [comment]
https://gunthy.org/index.php/topic,1417.0.html ?
Look like it's not working.
