### ISSUE TITLE
5055 Bot doesn't buy with full trading limit

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/Gunthy#56]
This has now happened many times in the past week. Why is the bot not using the full limit? Why in the world did the bot only buy $0.0099 worth of BTC?

![screen shot 2017-10-16 at 6 44 42 am](https://user-images.githubusercontent.com/4413670/31610435-ad5b302a-b23d-11e7-88e5-ea273ca7054c.png)

```
"pairs": {
   "poloniex": {
       "USDT_BTC": { "strategy": "bbstepgain", "override": { "TRADING_LIMIT": 5000 } }
   }
},
...
        "bbstepgain": {
                        "TRADING_LIMIT": 0.005,
                        "PERIOD": 5,
                        "BUY_LEVEL": 0.2,
                        "GAIN": 2,
                        "EMA1": 12,
                        "EMA2": 24,
                        "HIGH_BB": 20,
                        "LOW_BB": 30,
                        "STDV": 2,
                        "SMAPERIOD": 20,
                        "BUYLVL1": 0.6,
                        "BUYLVL2": 2,
                        "BUYLVL3": 70,
                        "SELLLVL1": 0.6,
                        "SELLLVL2": 0.6,
                        "SELLLVL3": 70,
                        "BUYLVL": 2,
                        "SELLLVL": 2,
                        "LASTPOINTS": 5,
                        "AVGPOINTS": 30,
                        "AVGMINIMUM": 0.0000001,
                        "PP_BUY": 0.00000001,
                        "PP_SELL": 0.12345678,
                        "PANIC_SELL": false,
                  	"DOUBLE_UP": false,
                        "STOP_LIMIT": 600,
                        "BUY_ENABLED": true,
                        "GUNTHY_API": false,
                        "MIN_VOLUME_TO_BUY": 0.0001,
                        "MIN_VOLUME_TO_SELL": 0.0001
                },
```

**Comment by paramecie** [comment]
Bad algorithm of calculation?
They buy 0.0001 but the fees are removed after, so remains 0.00099...

This should be calculated : qty=(limit_buy * feespercent)/price
Of course it's a bit more complicated, but this is the idea.

**Comment by utdrmac** [comment]
Right, so again, why so low when my limit_buy is $5000? That should have purchased about 0.8 BTC

**Comment by webservant7** [comment]
It looks to me like your TRADING_LIMIT is set to 0.005, which, since you are buying BTC with USDT, that limits your trade to 0.005 USDT. You need to set TRADING_LIMIT  to what I would call your base coin, (The coin you are using for the purchase) not the coin you are buying.

**Comment by utdrmac** [comment]
@webservant7 My TRADING_LIMIT is set to 5000, look at the override section.

**Comment by webservant7** [comment]
My bad.

**Comment by webservant7** [comment]
Could you copy and paste more of your pairs section? If that pair is not the last pair in that section then there may be a comma missing.

**Comment by utdrmac** [comment]
@webservant7 That's the only pair I trade on that instance. No commas are missing. And if there were, the bot would be producing JSON errors and nothing would be working.

**Comment by paramecie** [comment]
Didn't see the override, but I think it's your mistake.
It shoudl be written:

"USDT_BTC": 
{ "strategy": "bbstepgain",
"TRADING_LIMIT": 5000 }

Isn't it? I've never put "override".

**Comment by utdrmac** [comment]
@paramecie Look at the example provided by Gun himself and you'll see how to correctly do overrides. https://github.com/GuntharDeNiro/BTCT/releases/tag/v501

**Comment by paramecie** [comment]
Ah yes, the "doc everywhere system".
I've never seen this.
I don't think it should be so hard to be informed.

Anyway, I didn't use the override, and with buy_enabled, it seemed to work without.

Maybe you may try with no "override", and maybe discover it hasn't been implemented?

Maybe not - but then, the "override": { "TRADING_LIMIT": 5000 } doesn't work.

**Comment by utdrmac** [comment]
I know 'override' is indeed implemented because the bot, on bags, sometimes says 'unable to get bought price, please override with BOUGHT_PRICE' and when I add 'override': { 'BOUGHT_PRICE': 0.12345 }, that message goes away.

**Comment by paramecie** [comment]
Yes, but buy_enabled=false, if I remember well worked, without "override".
Then both may work.
Then it may work for some, and may not work for trading_limit.
Please try, or not.

I'm on 3.3.2 and have set it to sell only.

**Comment by utdrmac** [comment]
Doing this: `"USDT_BTC": { "strategy": "bbstepgain", "TRADING_LIMIT": 5000 }` did not produce any errors, but then again, neither did this: `"USDT_BTC": { "strategy": "bbstepgain", "TRADING_LIMIT": 5000, "FOOBARR": 1234 }`

Only way to know is wait for next buy cycle. But, given that there are 0 examples of that syntax (docs, github comments, and countless Telegram chats) and the fact that "override: BOUGHT_PRICE" does indeed work as I described above, I'm reluctant to believe this is the issue, especially when I've overridden trading_limit on my other bot instances with same syntax and it has worked just fine.

This isn't a configuration issue; this is a bot-programming-logic issue.

**Comment by paramecie** [comment]
I use the "foobar" technic to place comments in my pairs, with "note" for instance:

"BTC_AAA":
{
"strategy": "bbstepgain",
"note": "temporary setting, remove after 25/10 !!!"
}

It's easy to search "note" and read your "post-it"...

Apart this, you may be right, or not - the important fact is that it apparently doesn't work.

**Comment by paramecie** [comment]
BTW - 0.0099 doesn't correspond to any of your limits (like 0.0001)
I missed 1 zero..., so I don't understand this amount either.

But it could be a mismatch currency problem, like 0.0001 being counted in BTC?
Please calculate and if so, you've got the temporary fix: simply put the BTC amount?

(or reciprocally, I've no time to check all this, but you got the idea...)

**Comment by paramecie** [comment]
@utdrmac Then? Any news regarding my last message?

**Comment by utdrmac** [comment]
@paramecie Well, my next major buy from the bot was $4999.99997164 so I'm still counting this as a bug. Sometimes bot uses full TRADING_LIMIT, sometimes it uses fractions of the limit. So I'm waiting for @GuntharDeNiro to give his opinion on why the bot buys so little sometimes.

**Comment by paramecie** [comment]
OK thanks for the update.
