### ISSUE TITLE
5.0.5.5 RC WebUI can't launch

### ISSUE THREAD

**Issue by Singman33** [GuntharDeNiro/Gunthy#57]
After "npm install", running app.js give the following error :

```
# node app.js
/home/eric/gunbot/app.js:4
const { StringDecoder } = require('string_decoder');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by renereineke** [comment]
Hi Singman33, please paste the output of 
"which node" in console. I believe you installed an old version of node.js. Go for the LTS release v6.

**Comment by Singman33** [comment]
_I hate the fucking bastard markdown of this piece of githib shit_

**Comment by webservant7** [comment]
I got this same error yesterday when I was trying to run GB on a VPS without a Desktop or Browser installed. I found an article that related it to that scenario but didn't really give a solution. I installed a Desktop and Chrome browser and now it is working fine.

**Comment by Singman33** [comment]
That version (v4.2.6) is pretty old, trying to install a better one...

**Comment by rene-re** [comment]
You are probably running node.js on Ubuntu LTS?  You have to manually add the node.js repository of version 6 to apt. Then update and replace your node.js version. Should be good afterwards!

**Comment by Singman33** [comment]
Yep.
````
# curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
# apt-get install nodejs
# npm install
# node app.js
Gunthy listening on 127.0.0.1 port 3000!
````
