### ISSUE TITLE
(Bittrex) USDT-BTC buy orders are not executed

### ISSUE THREAD

**Issue by nomad5am** [GuntharDeNiro/Gunthy#60]
i'm currently playing with the USDT-BTC pair on Bittrex.
I noticed that the bot sells BTC to USDT when the target zone is met, but it's not buying back in!
Strategy:  stepgain

The log in the console  I get when the bot is supposed to buy BTC again makes no sense:
│ Callbacks       │ Waiting to cash some BTC │                                               

Why waiting to cash some BTC - to buy some BTC? USDT is already sufficient in my account and thats what the bot should do

Simple no? So, what is this error? 
No other pair shows this issues, only USDT-BTC shows this issue.

**Comment by murm78** [comment]
Even other USDT pairs are working fine?

**Comment by nobadysk** [comment]
I have same problem, after buy few USDT, gunbot start working...
