### ISSUE TITLE
5.0.5 95572 bot hangs (repost here)

### ISSUE THREAD

**Issue by paramecie** [GuntharDeNiro/Gunthy#7]
https://github.com/GuntharDeNiro/BTCT/issues/156

**Comment by JaimeCruzH** [comment]
Sometimes the program stop with the following error:

![gunboterror](https://user-images.githubusercontent.com/32025771/31047019-6bcd6d96-a5d9-11e7-8348-cc5fe071929b.PNG)

**Comment by paramecie** [comment]
Re-tested 5.0.5 right now, see post date - still hanging for 6 minutes after something like 10 minutes working.

Turned off, and back to 3.3.2.

**Comment by paramecie** [comment]
It happened again today (first time after many hours).
5.0.5.4, and using gunthy_api=true.

It just hang for half an hour, around 02 OCT 15:10 UTC
Should we better stop using gunthy server?

**Comment by paramecie** [comment]
Again 2 hours later. I set gunthy_api to false.

**Comment by utdrmac** [comment]
Experiencing this as well. Bot has just paused.
