### ISSUE TITLE
Unable to save change to settings on mobile clients

### ISSUE THREAD

**Issue by leewilkes** [GuntharDeNiro/Gunthy#74]
Using a mobile device, you are unable to save any changes made to settings. The save changes button is off the bottom of the screen & you can't scroll the window up to see it.
Tested on Android & iPhone - GB version 12.9.0

**Comment by GuntharDeNiro** [comment]
on the same note looks like candles on mobile are still black/white. Thank you

**Comment by GuntharDeNiro** [comment]
test

**Comment by yashspatel23** [comment]
Fixed mobile settings page issue and candles on mobile black/white issue. Fix will be included in one of the beta builds soon.
