### ISSUE TITLE
Saving Settings Loses exchanges and imap_listener from config.js

### ISSUE THREAD

**Issue by jalapenopuzzle** [GuntharDeNiro/Gunthy#75]
v12.9
I edited my settings on mobile and saved my config.
Contrary to issue #74 I was able to save the config.
Gunbot died.
Investigation revealed that the config.js file was saved without the following settings:
"bot": {
    "TOKEN": "XXX",
    "chat_id": "123456"
}
The following sections were saved as empty (previously they contained data):
"exchanges": {}
"imap_listener": {}

Reverting to backup

**Comment by yashspatel23** [comment]
@jalapenopuzzle unable to reproduce. I made a single change on mobile (toggled WATCH_MODE) and saved the changes. Config still remains in tact. 

Can you please provide steps to consistently reproduce the problem?

**Comment by cryptowally** [comment]
Had another user experience this issue. 

- Gunbot v12.9.9.2
- user editing config via mobile
- user changed TV_TRADING_LIMIT_CAP Had another user expe imap_listener section got removed 

Confirmed with diff from backups. Image follows

**Comment by cryptowally** [comment]
https://www.dropbox.com/s/8aezunzhhj12jkm/2019-06-15%2010.11.02.jpg?dl=0
