### ISSUE TITLE
Can't load Dashboard from Settings Page

### ISSUE THREAD

**Issue by jalapenopuzzle** [GuntharDeNiro/Gunthy#78]
v12.9 #guifix
Navigating from the Settings page (after editing and saving configuration) to the Dashboard page has no effect.
Ovserved on Linux using Chrome browser.

**Comment by jalapenopuzzle** [comment]
I am able to load the dashboard by re-loading the URL.

**Comment by jalapenopuzzle** [comment]
Navigating to Settings and then back to Dashboard works OK.
To trigger the problem you have to edit something and save the settings and then try to navigate back to Dashboard.

**Comment by yashspatel23** [comment]
@jalapenopuzzle If you make a change in settings, the bot restarts with the changes applied. If in those few seconds while the bot is restarting you attempt to navigate to the dashboard page, it won't load the page.

Can you try going to the settings page, making some modification, waiting 10-15 seconds and then going to the Dashboard page? If that resolves your problem, we can do better handling of that situation.

**Comment by jalapenopuzzle** [comment]
Yes I have noticed the dashboard loads if I wait longer before pressing the dashboard button.
