### ISSUE TITLE
Infinity Profit in Telegram message when selling with BOUGHT_PRICE override

### ISSUE THREAD

**Issue by jalapenopuzzle** [GuntharDeNiro/Gunthy#79]
v12.9
When selling with BOUGHT_PRICE override in effect, the telegram message says I made infinity profit.

The bug is that the sale did not generate infinity BTC.

At 2019/03/29 19:52:18 Gunbot Bittrex says: SELLING: BTC-ENG at bittrex
Using strategy: bb/gain
- Rate: 0.00013638 - Amount: 29.16018662
Averaged bought price was: 0.00000000
P/L is about : Infinity BTC (Infinity%).
(This is about Infinity USD)
BTC balance: 0.21561393
ENG balance: 29.16018662
Check this trade chart here (https://www.tradingview.com/chart/?symbol=bittrex:ENGBTC)
(GBRT-v12.9.0)

**Comment by GuntharDeNiro** [comment]
I've generated a commit for next beta build please provide feedback. Thank you
