### ISSUE TITLE
COUNT_SELL not working

### ISSUE THREAD

**Issue by JezPips** [GuntharDeNiro/Gunthy#84]
Pairs not deactivated after "x" trades as defined by this parameter. Works in v12.8.8 but not since. #corefix

**Comment by adrianthomson2142** [comment]
Also, is it possible to adjust the countsell feature to wait until AFTER the trade completes in case the order doesn't fill.

**Comment by GuntharDeNiro** [comment]
I revised the count_sell behaviour and to me it looks fine, I'll resume here when it isnt supposed to work:
1.- it doesn't work on Bitmex
2.- it doesn't work on Deribit
3.- it doesn't stop the pair after the last sell until we sold our entire quote
4.- if there are open orders to sell that pair

All of the above already behave like @adrianthomson2142 requested, it was changed in latest stable.
Please provide feedback: basically what is the expected behaviour is that the pair keeps cycling until all open sell orders are filled and if quote - keep quote - open orders <= MVTS.
Thank you.

**Comment by adrianthomson2142** [comment]
> 
> 
> I revised the count_sell behaviour and to me it looks fine, I'll resume here when it isnt supposed to work:
> 1.- it doesn't work on Bitmex
> 2.- it doesn't work on Deribit
> 3.- it doesn't stop the pair after the last sell until we sold our entire quote
> 4.- if there are open orders to sell that pair
> 
> All of the above already behave like @adrianthomson2142 requested, it was changed in latest stable.
> Please provide feedback: basically what is the expected behaviour is that the pair keeps cycling until all open sell orders are filled and if quote - keep quote - open orders <= MVTS.
> Thank you.

Expected behaviour is as you described, yet what it was doing, was disabling the pair without ensuring that the sell actually took place. It resulted in a drop of the Portfolio value (because that is tied to the active pairs) after the telegram message said it sold at profit. Yet, upon further investigation, I have a whole bunch of bags kicking around on the pairs that were deactivated by the countsell. 
Bags were then cleared manually.

**Comment by GuntharDeNiro** [comment]
@adrianthomson2142 wasn't this an issue reporting count_sell not working? So is It working or is it not working? Your initial report says it is not working. Now you saying it is working too much.

**Comment by adrianthomson2142** [comment]
> 
> 
> @adrianthomson2142 wasn't this an issue reporting count_sell not working? So is It working or is it not working? Your initial report says it is not working. Now you saying it is working too much.

Read that again Gunthar. It used to work. But it didn't actually verify the sell first. Now the last build it didn't work at all.

**Comment by GuntharDeNiro** [comment]
I cant reproduce this: I revised both the code and the logs, it actually disables the pair when count sell is reached AND quote balance is lower than MVTS. Please if you have a different behaviour I need logs, config and state json file. Thanks for reporting this

**Comment by JezPips** [comment]
I can reproduce this on Binance easily. I recall the guidelines for submission of logs, config and json files on the porno VIP channel and can't find them now. Please refresh my memory on the details and I'll get this to you asap.

**Comment by JezPips** [comment]
Attached are the logs.
[binance.BTC-AGI.log.1.gz](https://github.com/GuntharDeNiro/Gunthy/files/3026414/binance.BTC-AGI.log.1.gz)
[binance.BTC-AGI.log](https://github.com/GuntharDeNiro/Gunthy/files/3026415/binance.BTC-AGI.log)

Expected behaviour: Once Binance pair BTC-AGI trade has sold, disable trading for this pair after 1 sell. What happens is the trade sold but the pair is still on active trades. COUNT_SELL did not behave as intended.
[binance-BTC-AGI-state.json.txt](https://github.com/GuntharDeNiro/Gunthy/files/3026437/binance-BTC-AGI-state.json.txt)
[config.js.txt](https://github.com/GuntharDeNiro/Gunthy/files/3026438/config.js.txt)

**Comment by ecab081** [comment]
Having the same issue in V12.9 Ubuntu 18 on Binance using bbgain as strategy count sell is 1.  Happened to me today with the following pair attached KMD.   I attached a screenshot of my buys and sells with this coin for this example.  The bottom two buys were done manually by me.  Then today the bot sold which was great! However as you can see the bot bough the same pair again.  


![KMD](https://user-images.githubusercontent.com/34640189/55371864-c1ebdd80-54cd-11e9-9c0c-e4013bd9600a.JPG)



[binance.BTC-KMD.log](https://github.com/GuntharDeNiro/Gunthy/files/3032063/binance.BTC-KMD.log)

[binance-BTC-KMD-state.json.txt](https://github.com/GuntharDeNiro/Gunthy/files/3032065/binance-BTC-KMD-state.json.txt)

**Comment by Yooper101** [comment]
I can confirm that Count_Sell is not working. Had a bunch of final sells and pair was not disabled. I can produce logs, states when it happens again.

**Comment by t0xicfume** [comment]
^ Does not work for me as well. Any updates on fixing this issue?

**Comment by GuntharDeNiro** [comment]
@t0xicfume the next gunbot beta session is about to start, during the session all of reported bugs will be ANALyzed, thanks for reporting
