### ISSUE TITLE
Buy enabled false not working 5.0.5

### ISSUE THREAD

**Issue by camilores** [GuntharDeNiro/Gunthy#9]
When I unchecked Buy enabled in BBstepgain strategy to monitor gunbot it did buy and it dit it twice on top of that.

please fix this
Thanks

**Comment by selevanm** [comment]
Assume you did the 'unchecking' on the GUI configuration page?  Did you ensure to click the save button prior to testing?  The GUI will allow you to navigate away and not save your configuration. If using the configuration GUI also manually check the proper value was written to config.js - the more information you can give the better.

**Comment by Vaelek** [comment]
This happened to me as well. I had BUY_ENABLED true in the strategy, and overriden false on the coin, and it bought anyhow. It has not happened again since I set the strat to false and specifically enable on each coin I want to be buying.
