### ISSUE TITLE
Portfolio Value issue

### ISSUE THREAD

**Issue by adrianthomson2142** [GuntharDeNiro/Gunthy#92]
So it seems that the portfolio value must be calculated from the active pairs and nor from the wallet balances. If I disable a large bag, the value drops, and if I re-enable it, the value increases.

#Guifixes
Can we have it calculated from actual wallet balances instead of active pairs?
![image](https://user-images.githubusercontent.com/49071632/55265897-fd31a680-5258-11e9-8fba-8b4d84bc80a6.png)

**Comment by GuntharDeNiro** [comment]
this is a community decision I have marked it as feature request, will discuss in beta room with you all

**Comment by adrianthomson2142** [comment]
Expanding on the same feature request, Could we add somewhere in the dash, the total holdings on a per exchange basis? This would be useful to spot an exchange that has surplus capital that could be moved to another for balancing purposes.

So maybe:
Poloniex Value 5 BTC, 2 BTC free
Binance Value 2BTC, 0.01 BTC free...

We could then easilly spot some that should be moved around....
