### ISSUE TITLE
Chart Trade List has too few decimal places Kraken USDBTC

### ISSUE THREAD

**Issue by jalapenopuzzle** [GuntharDeNiro/Gunthy#93]
In the gunbot chart
Kraken USDBTC
In the list of trades at lower right
I am observing the number of decimal places in the trading volume.
The number of places alternates between 2 and 8 places, as shown in pictures below.
The trading volume must be shown to 8 places for BTC.

![image](https://user-images.githubusercontent.com/8386278/55269549-d02cd480-52e8-11e9-865e-3a78267b3841.png)

![image](https://user-images.githubusercontent.com/8386278/55269554-dae76980-52e8-11e9-823b-c3aff29ab138.png)

**Comment by GuntharDeNiro** [comment]
I generated a commit that should fix this, please test next beta build and provide feedback. Thank you.
