### ISSUE TITLE
Price To Sell too high when BOUGHT_PRICE set

### ISSUE THREAD

**Issue by jalapenopuzzle** [GuntharDeNiro/Gunthy#94]
I'm looking at Bittrex BTC-SALT.
There was a buy more than 3 months ago. I had to set BOUGHT_PRICE.
Now Gunbot computes an outlandish sell price, despite having a reasonable value for ABP.

![image](https://user-images.githubusercontent.com/8386278/55269632-c35cb080-52e9-11e9-8090-a2d2b317c264.png)
![image](https://user-images.githubusercontent.com/8386278/55269640-e1c2ac00-52e9-11e9-8c8e-382279ffdb00.png)
[bittrex-BTC-SALT-state.zip](https://github.com/GuntharDeNiro/Gunthy/files/3025015/bittrex-BTC-SALT-state.zip)

**Comment by GuntharDeNiro** [comment]
@jalapenopuzzle if the original buy is still present in your trading history and the exchanges is passing it on the api, you would need to use ITB.

**Comment by jalapenopuzzle** [comment]
There was a BOUGHT_PRICE set.
Removing it fixed the problem.
