### ISSUE TITLE
Gui shows NO Position but there is a position

### ISSUE THREAD

**Issue by crwthatonic** [GuntharDeNiro/Gunthy#95]
It says no position But it bought

![image](https://user-images.githubusercontent.com/23185111/55274662-8b6b6280-5315-11e9-8933-847b23394d84.png)

**Comment by GuntharDeNiro** [comment]
can you please post a screenshot from console? Thank you.

**Comment by crwthatonic** [comment]
Once the position of ETH opened, it showed both Long. Now in the gui it shows long but it's truly short.

![Long](https://user-images.githubusercontent.com/23185111/55298011-c5e01700-545d-11e9-8d84-f239443ba16b.PNG)
![xbt is short - eth is long](https://user-images.githubusercontent.com/23185111/55298013-c8427100-545d-11e9-8ff7-351aa3871d71.PNG)

When ETH has closed in profit, the position of XBT also shows no position.

![image](https://user-images.githubusercontent.com/23185111/55298069-0e97d000-545e-11e9-8900-c86560f2433c.png)
![image](https://user-images.githubusercontent.com/23185111/55298074-19526500-545e-11e9-9632-49809988b4b6.png)
