### ISSUE TITLE
Further graceful handling of erroneous Exchanges

### ISSUE THREAD

**Issue by Trashdog01** [GuntharDeNiro/Gunthy#96]
Ran into this issue which bought my entire instance to a halt.

![image](https://user-images.githubusercontent.com/33781517/55276878-15c2bf00-5334-11e9-9979-f2dcc02dcd54.png)

Can we improve on how graceful GB is with handling erroneous Exchanges so it can continue to running all other exchanges when one exchange is down (ie: disable exchange)?

Thankyou.

P.S. I attempted to disable all pairs for that exchange to try get around the issue but GB still wanted to connect. Only options I had was delete the exchange or turn off the bot until the issue is fixed.

**Comment by GuntharDeNiro** [comment]
i generated a commit please check next beta build and provide feedback ty
