### ISSUE TITLE
Tradingview Issue

### ISSUE THREAD

**Issue by adrianthomson2142** [GuntharDeNiro/Gunthy#98]
#corefix

Reporting on behalf of another user.

Tradingview alerts set up and working properly. Both buys and sells. Then add the same pair to Gunbot as an active pair (with buys and Sells override as disabled), then switch the TV_GB switch on.

Gunbot now seems to process buys, but refuses to process the sells.

His goal was to be able to use the GUI to "monitor" what is being done from his tradingview alerts on that pair. Once the TV_GB switch is off, it goes back to trading properly again.

Either a bug, or clarification on the TV_GB is required perhaps?

**Comment by adrianthomson2142** [comment]
User is also reporting that he is not getting sell messages, regardless of what his setup on the TV_GB is. 

The Multiple Base option being enables or disabled does not appear to have any effect.

**Comment by GuntharDeNiro** [comment]
@adrianthomson2142 please even if we use the new issue tracker we still need logs+config+statejson and all things we required in beta room, thank you

**Comment by adrianthomson2142** [comment]
> 
> 
> @adrianthomson2142 please even if we use the new issue tracker we still need logs+config+statejson and all things we required in beta room, thank you

It has been requested, I am trying to get it to include here. Hopefully it comes and/or this is reproducible.

**Comment by GuntharDeNiro** [comment]
i investigated a bit more on this issue, please test this and tell me if anything changes: run 2 separated instances, one with TV only and one with GB only in watch mode. Let me know if the issue disappears. Thank you

**Comment by adrianthomson2142** [comment]
> 
> 
> i investigated a bit more on this issue, please test this and tell me if anything changes: run 2 separated instances, one with TV only and one with GB only in watch mode. Let me know if the issue disappears. Thank you

Feedback from above user:

"I did this but unsuccessfully.  Was complaining about another bot running even tho I changed the ports properly.   I ran 2 bots prior to V12 all the time"
