### ISSUE TITLE
Kraken

### ISSUE THREAD

**Issue by adrianthomson2142** [GuntharDeNiro/Gunthy#99]
I notice wrong date for an open order
![image](https://user-images.githubusercontent.com/49071632/55280310-ab455b00-5302-11e9-9945-8b4adb7e4211.png)

json state file here
https://pastebin.com/vLHFjJjc

config used here
https://pastebin.com/2RKgk3gP

Couple log cycles here
https://pastebin.com/KnAGyyV8

Also shows this in console 
![image](https://user-images.githubusercontent.com/49071632/55280759-75a37080-5308-11e9-9409-bc745c8b32e3.png)

**Comment by GuntharDeNiro** [comment]
@adrianthomson2142

**Comment by GuntharDeNiro** [comment]
refactored kraken today, should be fixed, look at next beta build and provide feedback thank yu
